### ISSUE TITLE
Multisig component

### ISSUE THREAD

**Issue by encody** [NEARFoundation/near-contract-tools#35]
A few ways to implement multisig:

1. Follow a preexisting pattern (e.g. copy/translate from [core-contracts/multisig2](https://github.com/near/core-contracts/tree/master/multisig2)).
    - Pros: Logic & structures predefined, pattern is somewhat well-known (at least, not new)
    - Cons: Code is not very well-maintained, large, complex (complexity = opportunity for error), not NEP-standardized, and such a standard would likely take a long time due to the complexity
2. Implement our own: state machine (similar logic to core-contracts version)
    - Pros: We can clean up the logic from core-contracts a lot and simplify as necessary
    - Cons: Still relatively complex, and that comes with the same NEP approval difficulties.
3. Implement our own: tx queue/approval. The idea is to accept an arbitrary transaction-like blob and simply sign&send when quorum is reached.
    - Pros: Simpler than state machine model, since we don't have to [re-implement every possible action](https://github.com/near/core-contracts/blob/master/multisig2/src/lib.rs#L41-L73) in our own custom data structures. Management actions (e.g. add member) could be implemented as normal `#[private]` functions which are called via normal, reflexive `FUNCTION_CALL` proposal blobs. _Possibly_ easier to standardize as NEP since the logic is simpler.
    - Cons: Contract will have to do a little extra legwork (tx blob parsing) if it wants to implement any sort of limits on what sort of actions can be proposed, since this implementation would be written for generically signing _opaque_ transaction blobs. I'm not aware if this pattern has been implemented before (on NEAR), so this would be new technology. Requires more testing, and I'm not even absolutely sure it's possible since I've not written a PoC.
4. Implement our own: transaction signing protocol. Accept a transaction blob and an array of signatures (generated off-chain).
    - Pros: Probably the most straightforward implementation of multisig.
    - Cons: Suffers from the same lack of control as option 3 since it accepts an opaque blob. Requires some sort of off-chain mechanism for generating signatures.

**Comment by nearken** [comment]
@encody do you have effort estimations for each implementation? (e.g. would solution 3 be lower effort than re-implementing solution 1 because its simpler). 

Can you please describe the preventions/checks that will be required to limit actions and ensure security risks are mitigated for accepting arbitrary transaction-like blob for solution 3. Even if the pattern has not been implemented on NEAR, do you have any reference to another project that does use this pattern in their multisig implementation?

**Comment by encody** [comment]
@nearken

Assuming such an implementation is possible on NEAR (which I assume it is, just no PoC yet), I'd think option 3 is the simplest to implement from scratch. Keep in mind that for options 1&2, we have a pre-written, somewhat tested implementation to refer to already, so that would reduce development time there.

I'm not sure there's really an Ethereum analogue to options 1&2 since Ethereum just has transactions, but not action kinds (beyond EVM opcodes).

Option 3 is approximately equivalent to [this Solidity multisig implementation from ConsenSys Mesh](https://github.com/ConsenSysMesh/MultiSigWallet/blob/master/MultiSigWalletWithDailyLimit.sol).

Option 4 is approximately equivalent to [Gnosis Safe](https://github.com/safe-global/safe-contracts/blob/main/contracts/GnosisSafe.sol).

**Comment by encody** [comment]
> Can you please describe the preventions/checks that will be required to limit actions and ensure security risks are mitigated for accepting arbitrary transaction-like blob for solution 3.

Basically the contract would need to deserialize the blob into a transaction struct. This should be straightforward since [nearcore `Transaction` is both `Deserialize` and `BorshDeserialize`](https://github.com/near/nearcore/blob/master/core/primitives/src/transaction.rs#L22-L38). So not _too_ bad.

However, it's a multisig contract. People should be checking the things they sign before they sign them, so although we will make allowances in the architecture to allow for limits/checks, the checks will ultimately rest with the signers, unfortunately.

**Comment by encody** [comment]
Working on an idea very closely related to this today. Something like a confirmation accumulator. This could modularize the problem.

**Comment by nearken** [comment]
@encody I think a useful exercise would to review past discussions in NEAR ecosystem regarding multisig. 

Some other NEAR-related multisig issue conversations:
- https://github.com/near/near-wallet/issues/423
- https://github.com/near/core-contracts/pull/66
- https://github.com/near/core-contracts/pull/12

I need to read up on ConsenSys Mesh but I do like the idea of using a pattern that has gained popularity in other ecosystems. I am familiar with Gnosis Safe and think this could be a promising approach. High level, I would suggest determining pros/cons between two options to either refactor / simplify [core-contracts/multisig2](https://github.com/near/core-contracts/tree/master/multisig2) or convert Gnosis Safe implementation because I see simplicity as huge benefit and key factor in the design decision regarding what pattern to implement.

**Comment by encody** [comment]
Let's say one of the multisig members approves an action and later changes his mind, _before_ the action has been executed. Should the member be able to revoke his prior approval?

Multisig rejections:
1. Should they be supported by this implementation?
    - I think that not supporting them is a completely legitimate option. The member has already signed his approval: tough. There are no take-backsies in blockchain town.
2. Let's assume we decide to support revocations. Should a revocation be permissioned?
    - Let's say multisig members are assigned the "Multisig" role. Actor "A" has the "Multisig" role. Actor "A" approves a multisig action. The "Multisig" role is revoked from Actor "A". Does Actor "A" still have the ability to revoke his prior approval? Due to the modular design of this library, I don't think that automatically removing the approval is an option.
    - If revocations are _not permissioned_ (Actor "A" can still revoke prior approval), this possibly partially violates the invariant that the state of a multisig component can only be modified by its members. Although I don't see an immediate downside to this, this may cause users of the library to incorrectly assume its functionality.
    - If revocations are _permissioned_, how should we deal with "hanging approvals" (are they even a problem)?

**Comment by ryancwalsh** [comment]
@encody Good questions. Personally I think I'm leaning towards option 1 unless we hear good reasons for adding more complexity. We're don't want to add more challenges right now than necessary.

**Comment by encody** [comment]
What should be the criteria for request deletion? I see three simpler options:
1. Allow deletion by any approval-eligible member only when there are zero approvals (current model). However, now that we do not allow members to rescind their approvals, it would be impossible to delete a request that has gotten at least one approval.
2. Maintain a separate list of "delete request" votes (with a corresponding "deletion threshold") vs. approval votes
3. Allow deletion by any approval-eligible member after some timeout

I think option 3 is the best, because it is fairly simple, and it is also probably what most users would expect.

**Comment by encody** [comment]
@ryancwalsh When the request is created, record the current network time. The multisig component contains a "validity period" value. When the difference between the current network time and the the request's creation time exceeds the validity period, the request is considered "expired" and could be, for example, deleted. I imagine the duration would be something like 1-7 days in network time (using `near_sdk::env::block_timestamp_ms()` or something like that).

**Comment by ryancwalsh** [comment]
@encody ok, to see if I understand correctly:

1. We would have defined some arbitrary constant called something like validity_period in the contract as something like 1-7 days
2. someone creates a request (I think of it as a proposal)
3. inherent in that request (and not needing to be stored somewhere separately) is its timestamp
4. any approver can attempt to delete any request, and upon deletion attempt, the contract will check whether enough time has elapsed between the request timestamp and now to exceed validity_period. If yes, the deletion happens. Otherwise it returns an error.

And the timestamps of the request and "now" are both NEAR network timestamps since blockchains have their own definition of time which won't always synchronize perfectly with the real world.

Did I get any of that wrong?

It sounds good to me.

**Comment by encody** [comment]
@ryancwalsh That is exactly correct.

**Comment by encody** [comment]
@ryancwalsh As of dccaa5132011cd3e756a108aefa686bde548205b , #39 implements the aforementioned workflow.

**Comment by ryancwalsh** [comment]
@encody `ryancwalsh closed this as completed in #39 1 minute ago` was automatic. Just giving you a heads-up in case that's not what you wanted (but it probably was).

**Comment by encody** [comment]
@ryancwalsh All good
