### ISSUE TITLE
Can `near-contract-tools` be `#[no_std]`? Should it be?

### ISSUE THREAD

**Issue by encody** [NEARFoundation/near-contract-tools#51]
I think "yes" and "possibly". Smart contract programming is pretty similar to embedded systems programming.

**Comment by nearken** [comment]
@encody I think "yes" and "no" but I may be lacking context and understanding about the pros of using core-crate instead of std-crate. 

What type of operations in `near-contract-tools` would use the language primitives API that allow use of low level instruction set? 

From what I've read about `#[no_std]` it seems to increase complexity and is less convenient. I would lean towards going with simplicity unless there is any functionality that can't be accomplished with std which is needed 

Pulling from this thread: [[Noob] What exactly is #![no_std], and why is it so useful sometimes to be without it?](https://www.reddit.com/r/rust/comments/9eyc21/comment/e5u1ddx/?utm_source=share&utm_medium=web2x&context=3) Is motiviation behind this question just that `std` is not used throughout the library?
