### ISSUE TITLE
Re-export traits at top level to show them in top level doc page

### ISSUE THREAD

**Issue by twitu** [NEARFoundation/near-contract-tools#73]
The top level [doc page](https://docs.rs/near-contract-tools/latest/near_contract_tools/) for the package shows the modules but not the traits it offers.

Since the primary aim of this repo is to capture common patterns as traits. They can be exposed at the top level. This is will also expose those traits in the top level documentation. This can be done by re-exporting them from `lib.rs`.

Again we can take a cue from [serde docs](https://docs.rs/serde/latest/serde/) and [lib.rs](https://github.com/dtolnay/serde/blob/07ba7ea8dd66fe240aff82456c01e9aeda47509c/serde/src/lib.rs#L265-L268)

**Comment by encody** [comment]
With the resolution of this issue comes the possibility for future item name collisions. For example, the `approval` module has a trait called `Action`, which is a name I could see being easily used elsewhere. Exporting this name at the crate level could then lead to confusion / collision / breaking changes if we ever introduce a component that also uses an item called `Action`. However, it seems that [the Rust community generally prefers to use the path as a disambiguating prefix](https://internals.rust-lang.org/t/does-the-avoid-prefixing-the-type-with-the-name-of-the-module-style-rule-still-apply/12819).

So, it should be decided:
1. Whether to fix this issue as recommended above.
2. If we decide to fix this issue as recommended, either:
    1. We only export a limited selection of the traits. Which ones?
    2. We prefix the item names with the module names. I don't like this because it is superfluous (that information already exists in the form of the canonical module path, e.g. `nep141::Nep141Hook` as opposed to `nep141::Hook`) and it goes against Rust convention.

However, this also exposes an internal naming inconsistency: Things like [`Nep141Hook`](https://github.com/NEARFoundation/near-contract-tools/blob/95478187dcf9dd7043eca5e48db0c1d36b3b7175/src/standard/nep141.rs#L168), etc. would be renamed to merely `Hook`. I'm _personally_ okay with this change (breaking as it may be) because of the reasons given in 2.2 above.

@ryancwalsh As arbiter of the properly verbose, do you have input on this topic?

**Comment by ryancwalsh** [comment]
Thanks for raising this, @twitu . And thanks for the options, @encody .

Remember, I have nearly zero Rust experience, so it would probably be best to seek others' opinions.

From my instinct, my answer to # 1 is leaning towards Yes. 

But I've read 2.ii. and the "However" sentence many times and am having trouble following along.  What is "However" responding to? And what does the "this" in that sentence refer to?

I don't know that I really understand the problem of naming things like `nep141::Hook` (which to me seems a bit better than `nep141::Nep141Hook` which does look redundant). If there is another `Hook` in the same crate, does that really cause a "collision"? 

Wouldn't it just mean that people who are importing those functions would need to specify the longer (clearer) import name to disambiguate? 

What would be an example of how that would work? What are the downsides?

**Comment by twitu** [comment]
While working on #74, I've observed a couple of other things that are relevant here.

This crate offers two main items traits and macros for various patterns. However it's the macros that are really important and will be used the most. They reduce boilerplate and make implementing contracts easy. Considering this, it's the macros that should be highlighted in the top level docs because it's most likely that the someone looking at the docs will want to read about the macros.

The traits are always there and someone can derive a custom implementation, but that looks like an uncommon case. Still the traits should be documented well. Which brings me to the second observation.

Most of the components are actually made of two traits one for internal methods and one for external functions for e.g. `Owner` and `OwnerExternal`. Both together make the owner component useful, and the even derive macro for Owner derives them both.

Considering this, exporting traits at the top level may not be the best idea because the two traits together provide the complete functionality. So exporting the modules at the top level, along with descriptive module level docs (in progress in #74) seems to be a good fit here. This is currently the state of the doc so no changes are needed for this.

An immediate improvement to consider is to [hyperlink items](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html) everywhere in the docs and especially hyperlink the traits in the single line description shown for the derive macros [here](https://docs.rs/near-contract-tools/0.6.1/near_contract_tools/#derives).

**Comment by ryancwalsh** [comment]
@twitu Great!

**Comment by encody** [comment]
Sounds like we are _not_ implementing the titular suggestion, but instead 1) a uniform naming convention, and 2) a documentation improvement. Is this correct? If so, this issue should probably be closed and two new ones created.

**Comment by twitu** [comment]
Consistent naming is being discussed in #70
